branch-defaults:
  develop:
    environment: youtube-music-download
deploy:
  artifact: ./Archive.zip
environment-defaults:
  youtube-music-app-dev:
    branch: null
    repository: null
global:
  application_name: youtube-music-app
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
