service: youtubedownloadapp

frameworkVersion: '2'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  region: eu-west-2
  timeout: 30
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:PutObject"
         - "s3:GetObject"
       Resource:
         Fn::Join:
           - ""
           - - "arn:aws:s3:::"
             - Ref: "ServerlessDeploymentBucket"
             - "/*"


functions:
  get_tracks:
    handler: handler.get_tracks
    events:
      - http:
          path: get_tracks
          method: post
          cors: true
  download_tracks:
    handler: handler.download_tracks
    events:
      - http:
          path: download_tracks
          method: post
          cors: true
    timeout: 30 # default is 6 sec, max is 900 sec, 30sec dor API gateway
  download_zip:
    handler: handler.download_zip
    events:
      - http:
          path: download_zip
          method: get
          cors: true