service: youtubedownloadapp

frameworkVersion: '2'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  region: eu-west-2
  timeout: 30
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:PutObject"
         - "s3:GetObject"
       Resource:
         Fn::Join:
           - ""
           - - "arn:aws:s3:::"
             - Ref: "ServerlessDeploymentBucket"
             - "/*"


functions:
  get_songs:
    handler: handler.get_songs
    events:
      - http:
          path: get_songs
          method: post
          cors: true
  convert_songs:
    handler: handler.convert_songs
    events:
      - http:
          path: convert_songs
          method: post
          cors: true
    timeout: 30 # default is 6 sec, max is 900 sec, 30sec for API gateway
  download_songs:
    handler: handler.download_songs
    events:
      - http:
          path: download_songs
          method: get
          cors: true